version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-secret-key-here
      - DATABASE_URL=./databases/pizza.db
    volumes:
      - ./databases:/app/databases
      - ./public:/app/public
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - JWT_SECRET=dev-secret-key
      - DATABASE_URL=./databases/pizza.db
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    profiles:
      - dev
